# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r_github_packages:
  - jimhester/lintr
script: 
  - R -f tests/render_rmds.R
after_success:
  - Rscript -e 'lintr::lint("Analysis_of_BLAST_Results.Rmd")'

